### ISSUE TITLE
Migrate away from gulp-util

### ISSUE THREAD

**Issue by mcman2017** [facebook/fbjs#284]
Please use one/all of the following gulp replacements below:
using the following API replacements:
gutil.File => https://www.npmjs.com/package/vinyl
gutil.replaceExtension => The .extname property on Vinyl objects or https://www.npmjs.com/package/replace-ext
gutil.colors => https://www.npmjs.com/package/ansi-colors
gutil.date => https://www.npmjs.com/package/date-format
gutil.log => https://www.npmjs.com/package/fancy-log
gutil.template => https://www.npmjs.com/package/lodash.template
gutil.env => https://www.npmjs.com/package/minimist
gutil.beep => https://www.npmjs.com/package/beeper
gutil.noop => https://www.npmjs.com/package/through2
gutil.isStream => Use the .isStream() method on Vinyl objects
gutil.isBuffer => Use the .isBuffer() method on Vinyl objects
gutil.isNull => Use the .isNull() method on Vinyl objects
gutil.linefeed => Use the string '\n' in your code
gutil.combine => https://www.npmjs.com/package/multipipe
gutil.buffer => https://www.npmjs.com/package/list-stream
gutil.PluginError => https://www.npmjs.com/package/plugin-error

**Comment by zpao** [comment]
This was fixed in #279 (and just published)

**Comment by demurgos** [comment]
@zpao 
[According to npm](https://www.npmjs.com/package/fbjs-scripts), `gulp-util` is still used. Could you check that the published version? We're still getting issues on the Gulp side from users complaining about the deprecation warning caused by `fbjs-scripts`.

**Comment by zpao** [comment]
Thanks for catching that @demurgos! I was on a branch based on old master and totally messed that up. Luckily it was identical to v0.8.1 so no harm done. I just shipped v0.8.3 (double checking everything this time around).

**Comment by demurgos** [comment]
Looks good, thanks!
